### ISSUE TITLE
comments for lexedata.exporter.cognates for minimal dataset

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#172]
I just tried to export cognates for Bantu and the script doesn't work. I think it requires a cognateset table (Bantu has only forms and languages). 
this is what I am getting (which is not very informative):
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 426, in <module>
    E = ExcelWriter(
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 40, in __init__
    self.set_header()
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 56, in set_header
    c_id = self.dataset["CognatesetTable", "id"].name
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 578, in __getitem__
    raise KeyError(table)
KeyError: 'CognatesetTable'

I have also noticed this first warning at the top "possible nested set at position 12" a couple more times with this dataset. I don't know what it means.

**Comment by Anaphory** [comment]
`lexedata.exporter.cognates` should test whether you have a separate cognate table, and if you don't refer you to `lexedata.edit.add_cognate_table` to add one.
