### ISSUE TITLE
errors with lexedata.exporter.phylogenetics with minimal dataset

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#173]
I got an error trying to export the Bantu dataset to nexus (however, I had forgotten to specify nexus, I don't know if there is a default)
`natalia:test-Bantu$python -m lexedata.exporter.phylogenetics --coding rootmeaning
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
WARNING:lexedata:Your dataset has a cognatesetReference in the FormTable. Consider running lexedata.edit.explict_cognate_judgements to create an explicit cognate table, if this is your dataset.
8767it [00:00, 25390.61it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 834, in <module>
    ] = read_cldf_dataset(dataset, code_column=args.code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 90, in read_cldf_dataset
    return read_wordlist(dataset, code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 190, in read_wordlist
    if "LanguageTable" in dataset:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 572, in __getitem__
    uri = term_uri(table, terms=TERMS.by_uri)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/terms.py", line 23, in term_uri
    if not name.startswith(ns):
AttributeError: 'int' object has no attribute 'startswith'`

Then, I used the command more fully and I got this:
`natalia:test-Bantu$python -m lexedata.exporter.phylogenetics --coding rootmeaning --format nexus -o Bantu.nex
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
WARNING:lexedata:Your dataset has a cognatesetReference in the FormTable. Consider running lexedata.edit.explict_cognate_judgements to create an explicit cognate table, if this is your dataset.
8767it [00:00, 25263.09it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 834, in <module>
    ] = read_cldf_dataset(dataset, code_column=args.code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 90, in read_cldf_dataset
    return read_wordlist(dataset, code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 190, in read_wordlist
    if "LanguageTable" in dataset:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 572, in __getitem__
    uri = term_uri(table, terms=TERMS.by_uri)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/terms.py", line 23, in term_uri
    if not name.startswith(ns):
AttributeError: 'int' object has no attribute 'startswith'`

**Comment by nataliacp** [comment]
I tried to run the command suggested to get a Cognates.csv (i think), but it must have been renamed or it doesn't exist any more. I tried various plausible names!

**Comment by nataliacp** [comment]
just an update, that after fixing the Bantu dataset with trivial tables, I still get the same error. However, there is a counter that makes it to 100% (I don't know of what), but it doesn't create a file 
`natalia:test-Bantu$python -m lexedata.exporter.phylogenetics --coding rootmeaning --format nexus
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
WARNING:lexedata:Your dataset has a cognatesetReference in the FormTable. Consider running lexedata.edit.explict_cognate_judgements to create an explicit cognate table, if this is your dataset.
100%|███████████████████████████████████████████████████████████████████████| 8158/8158 [00:00<00:00, 19473.15it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 834, in <module>
    ] = read_cldf_dataset(dataset, code_column=args.code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 90, in read_cldf_dataset
    return read_wordlist(dataset, code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 190, in read_wordlist
    if "LanguageTable" in dataset:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 572, in __getitem__
    uri = term_uri(table, terms=TERMS.by_uri)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/terms.py", line 23, in term_uri
    if not name.startswith(ns):
AttributeError: 'int' object has no attribute 'startswith'`

**Comment by nataliacp** [comment]
I just tried to get rid of the cognatesetReference n the formTable, since I have now a trivial cognates.csv and a cognateset.csv made by hand. Cldf validate ran without any warnings. However, the exporter still gives me apparently the same error. I tried with bantu-to-edictor branch and with master. 

`natalia:test-Bantu$python -m lexedata.exporter.phylogenetics --format nexus --coding rootmeaning
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
 20%|█████████████▊                                                        | 8158/41315 [00:00<00:00, 48529.16it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 834, in <module>
    ] = read_cldf_dataset(dataset, code_column=args.code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 90, in read_cldf_dataset
    return read_wordlist(dataset, code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 190, in read_wordlist
    if "LanguageTable" in dataset:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 572, in __getitem__
    uri = term_uri(table, terms=TERMS.by_uri)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/terms.py", line 23, in term_uri
    if not name.startswith(ns):
AttributeError: 'int' object has no attribute 'startswith'`

**Comment by nataliacp** [comment]
This is resolved after Gereon's fix (166 on bantu-to-edictor branch). However, I haven’t tried yet with the simpler version of the dataset (without all the trivial tables).

**Comment by Anaphory** [comment]
`Consider running lexedata.edit.explict_cognate_judgements to create an explicit cognate table, if this is your dataset.`: These days, that script is called `lexedata.edit.add_cognate_table`; we should check the warning and put it in a visible spot where it doesn't get drowned by other things.
