### ISSUE TITLE
lexedata.edit.replace_id not working

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#195]
I tried the replace_id to replace the existing language_ids with glottocodes in the Bantu dataset, and it is not doing what I expect. 
I typed `python -m lexedata.edit.replace_id languages.csv Language_ID Glottocode` language_id is the current id column and I want the Glottocode column to take up this role. The script seems to run, exits without an error and reports:
`INFO:lexedata:Writing languages.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'Language_ID'} in forms.csv…
8767it [00:00, 21753.91it/s]                                                                                                             
INFO:lexedata:Writing forms.csv back to file…`
- [x] However, when I checked forms.csv, it still contains the old ids and no glottocodes
- [x] languages.csv seems unchanged (and I don't actually understand why it is rewritten by the script)
- [x] I expected that the json file would be modified to reflect the change in ID, but it is unchanged as well. 

I also tried inverting the two columns in the command thinking that maybe the help is not written correctly, but I don't get any changes either. Finally, when I verified with git, languages.csv and forms.csv show up as modified, but not the json file.

**Comment by nataliacp** [comment]
I tried this again and now it gets stuck. 
`INFO:lexedata:Updating ids of Table(common_props={'dc:conformsTo': 'http://cldf.clld.org/v1.0/terms.rdf#LanguageTable', 'dc:extent': 84}, at_props={}, aboutUrl=None, datatype=None, default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, dialect=None, notes=[], tableDirection='auto', tableSchema=Schema(common_props={}, at_props={}, aboutUrl=None, datatype=None, default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, columns=[Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#name"), required=True, separator=None, textDirection=None, valueUrl=None, name='Language', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='Glottolog_Name', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#glottocode"), required=None, separator=None, textDirection=None, valueUrl=None, name='Glottocode', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='Guthrie_Code', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='ISO_Code', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#comment"), required=None, separator=None, textDirection=None, valueUrl=None, name='comment', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#id"), required=True, separator=None, textDirection=None, valueUrl=None, name='Language_ID', suppressOutput=False, titles=None, virtual=False)], foreignKeys=[], primaryKey=['Language_ID'], rowTitles=[]), transformations=[], url=<csvw.metadata.Link object at 0x7fe741d1e310>, _fname=None, suppressOutput=False)
 96%|██████████████████████████████████████▌ | 81/84 [00:00<00:00, 22607.04it/s]
INFO:lexedata:Writing languages.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'Language_ID'} in forms.csv…
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/replace_id.py", line 36, in <module>
    update_ids(
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/simplify_ids.py", line 169, in update_ids
    for row in cli.tq(
TypeError: tq() missing 1 required positional argument: 'task'`
