### ISSUE TITLE
lexedata.exporter.cognates error

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#196]
I tried the cognate exporter for Bantu and I got an error (it looks simple, but I don't know if i can do anything to the dataset to avoid it). 
`natalia:cldf$python -m lexedata.exporter.cognates Cognates.xlsx
AttributeError: 'Namespace' object has no attribute 'status_update'`

**Comment by nataliacp** [comment]
I tried again and now it gets stuck elsewhere!
`INFO:lexedata:Writing languages to excel header
100%|███████████████████████████████████████| 81/81 [00:00<00:00, 197982.88it/s]
INFO:lexedata:Wirting cognates and cognatesets to excel
100%|█████████████████████████████████████| 1455/1455 [00:00<00:00, 3520.87it/s]
INFO:lexedata:Write singleton cognatesets to excel
100%|███████████████████████████████████| 1455/1455 [00:00<00:00, 155880.26it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 460, in <module>
    E.create_excel(
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 238, in create_excel
    c_cogset_name = self.dataset["CognatesetTable", "name"].name
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 379, in __getitem__
    raise KeyError(column)
KeyError: 'name'
`
