### ISSUE TITLE
help of report.segments_inventories is not working

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#265]
I get only this:
```  from collections import (```
Also, the command needs to be segment_inventories (not both words in plural).

**Comment by nataliacp** [comment]
I get the same output for report.judgements. 
Maybe we do not have descriptions at all for these commands because they are reports? Shouldn't there be a minimal thing though?

**Comment by nataliacp** [comment]
I tried this again (with segment_inventories) and this is what I get: 
`Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/segment_inventories.py", line 14, in <module>
    from lexedata.edit.add_segments import bipa
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/add_segments.py", line 89, in <module>
    "oː́": str(bipa["long rounded close-mid back with-high_tone vowel"]),
  File "/Users/natalia/.local/lib/python3.8/site-packages/pyclts/util.py", line 31, in __getitem__
    return self.resolve_sound(sound)
  File "/Users/natalia/.local/lib/python3.8/site-packages/pyclts/transcriptionsystem.py", line 278, in resolve_sound
    return self._from_name(string)
  File "/Users/natalia/.local/lib/python3.8/site-packages/pyclts/transcriptionsystem.py", line 163, in _from_name
    raise ValueError('string contains unknown features')
ValueError: string contains unknown features`

**Comment by nataliacp** [comment]
the command (not only the help) is not running either, I get the same thing with two datasets

**Comment by Anaphory** [comment]
Ooof. That sounds like an issue with different CLTS versions. I'll have to chat to you about that.

**Comment by nataliacp** [comment]
now on the bantu dataset it says: 
`Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/segment_inventories.py", line 14, in <module>
    from lexedata.edit.add_segments import bipa
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/add_segments.py", line 32, in <module>
    bipa = clts.api.bipa
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/api.py", line 23, in bipa
    return self.transcriptionsystem('bipa')
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/api.py", line 80, in transcriptionsystem
    if key in self.transcriptionsystem_dict:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/api.py", line 77, in transcriptionsystem_dict
    return {ts.id: ts for ts in self.iter_transcriptionsystem()}
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/api.py", line 77, in <dictcomp>
    return {ts.id: ts for ts in self.iter_transcriptionsystem()}
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/api.py", line 69, in iter_transcriptionsystem
    yield TranscriptionSystem(
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pyclts/transcriptionsystem.py", line 70, in __init__
    sound = cls(ts=self, **item)
TypeError: __init__() got an unexpected keyword argument 'laterality'`

**Comment by nataliacp** [comment]
edit.add_segments is also affected by the same issue

**Comment by Anaphory** [comment]
Our tests install version 2.0.0 of CLTS        (cd ~/.config/cldf/ && [ -d clts ] || git clone -b v2.0.0 --depth 1 https://github.com/cldf-clts/clts.git)
