### ISSUE TITLE
error when reporting coverage on arawak dataset

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#278]
this is what I got just typing the command without any optional arguments
```WARNING:lexedata:ParameterTable doesn't contain a column 'Primary'. Primary concepts couldn't be loaded. Loading all concepts.
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/coverage.py", line 253, in <module>
    data, header = coverage_report(
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/coverage.py", line 108, in coverage_report
    for c in with_concept:
TypeError: 'WorldSet' object is not iterable```

**Comment by nataliacp** [comment]
I got the same error with the test bantu dataset. With the actual bantu dataset I got a different thing: 
```Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/coverage.py", line 253, in <module>
    data, header = coverage_report(
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/coverage.py", line 54, in coverage_report
    if foreign_key.reference.resource == dataset["ParameterTable"].url:
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 367, in __getitem__
    raise KeyError(table)
KeyError: 'ParameterTable'```
I think this means that I don't have a parameter table, which is indeed the case according to the json file. After adding a parameter table, simplifying ids and validating (not extended though) I get now the same error. 
By the way, I love your warnings everywhere and advice what to do next!

**Comment by Anaphory** [comment]
I should have fixed these two now on the Fixes branch.

**Comment by nataliacp** [comment]
indeed, it is fixed on fixes and it works on both datasets. The only thing missing is the default setting for the --missing argument. it is KNOWN right?

**Comment by Anaphory** [comment]
Yes.
