### ISSUE TITLE
report.nonconcatenative_morphemes

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#281]
- [ ] how is this different from the --strict option of the report.judgements?
- [ ] when running it for arawak I got this: `INFO:lexedata:Caching table FormTable
40675it [00:04, 8857.70it/s]                                                                                                                          
WARNING:lexedata:In judgement 11550-ANANAS COMOSUS5, segments 1:4 are associated with cognate set ANANAS COMOSUS5, but were already in ACCIPITRIDAE SP.8.
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 120, in <module>
    merge_pairs = segment_to_cognateset(
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 73, in segment_to_cognateset
    [form["segments"][s] for s in segments_judged]
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 73, in <listcomp>
    [form["segments"][s] for s in segments_judged]
IndexError: list index out of range`

**Comment by nataliacp** [comment]
sorry for reopening this. can you briefly explain the difference so I can write about it in the manual? 
Also, I keep getting a similar error with Arawak (on fixes and master), but the arawak dataset has some issues (missing cognateset ID in a few lines) so maybe it's that?
```
INFO:lexedata:Caching table FormTable
40675it [00:04, 8899.19it/s]                                                                                                                          
WARNING:lexedata:In judgement 11550-ANANAS COMOSUS5, segments 1:4 are associated with cognate set ANANAS COMOSUS5, but were already in ACCIPITRIDAE SP.8.
Traceback (most recent call last):
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 89, in segment_to_cognateset
    cognatesets = which_segment_belongs_to_which_cognateset[
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 124, in <module>
    merge_pairs = segment_to_cognateset(
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/nonconcatenative_morphemes.py", line 94, in segment_to_cognateset
    f"In judgement {j[c_cognate_id]}, segment slice {j[c_cognate_slice]} points outside valid range 1:{len(form[c_form_segments])}."
KeyError: 'Segments'
```
