### ISSUE TITLE
error in exporter.cognates

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#334]
I tried to export cognates for Hilde's dataset and I got this:
`
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 538, in <module>
    or dataset["CognatesetTable", args.sort_cognatesets_by].name
AttributeError: 'Table' object has no attribute 'name'
`
this is a dataset with trivial tables so there are no cognateset names. Shouldn't it just ouput everything by ID?

**Comment by nataliacp** [comment]
this happened again now with the large Bantu dataset, and I have another idea. When lexedata adds a language table it puts the same thing for language_ID and language_Name. I think it should do the same by default when it creates a cognatesetTable. This way there will be a name field in the table. For now, I will add a duplicate name field by hand.

**Comment by nataliacp** [comment]
Probably I am understanding the error wrong. I added a name column in the CognatesetTable, I also modified the json file accordingly, and still I get the same error when I try to export cognates.xlsx
