### ISSUE TITLE
error in importer.excel_long_format

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#336]
I tried importing the first new Bantu language and I got this
```
INFO:lexedata:No sheets specified explicitly. Parsing sheets: None
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_long_format.py", line 433, in <module>
    ignore_missing=args.ignore_missing_excel_columns,
AttributeError: 'Namespace' object has no attribute 'ignore_missing_excel_columns'

**Comment by nataliacp** [comment]
I fixed it!!! I am merging it now. 
But now I get stuck elsewhere:
```
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_long_format.py", line 428, in <module>
    report = add_single_languages(
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_long_format.py", line 330, in add_single_languages
    for lang, subreport in read_single_excel_sheet(
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_long_format.py", line 125, in read_single_excel_sheet
    c_f_value = db.dataset["FormTable", "value"].name
  File "/Users/natalia/opt/anaconda3/lib/python3.8/site-packages/pycldf/dataset.py", line 379, in __getitem__
    raise KeyError(column)
KeyError: 'value'`
