### ISSUE TITLE
unexpected behavior with simplify ids

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#349]
Importing a new language with a ID that violates json requirements blocks simplify ids. The help of importer long_format states that simplify_ids should be able to handle this, but instead we get an error

**Comment by Sara2882** [comment]
<img width="873" alt="Capture" src="https://user-images.githubusercontent.com/97735566/163410144-69f97927-3e78-4dba-a0bd-53dada8727ed.PNG">

**Comment by Anaphory** [comment]
Oh, dammit! I could have forseen that issue. I even had an idea how to avoid it when we first discussed it. I'll give you a hot fix in a moment.

**Comment by Anaphory** [comment]
Uff, I'll have to dig deeper. The solution I was anticipating is already in the code:

https://github.com/Anaphory/lexedata/blob/8e9d820502ddb00a2f49dadf9e52151ad0d99657/src/lexedata/edit/simplify_ids.py#L63-L65

But if you still run into it, I'm overlooking something.

**Comment by Anaphory** [comment]
Ah, I have a suspicion. I guess I'm opening the datatype format of LanguageTable's ID, but not of FormTable's LanguageID. Hmmmmm. :thinking:

**Comment by nataliacp** [comment]
we bypassed it for now, but it happens again when using the switch --concept-name because it adds illegal ids again and they cannot be simplified.

**Comment by nataliacp** [comment]
this is still an issue in the current release. we tried simplify_ids in the whole dataset and we get a value error for forms.csv

**Comment by Sara2882** [comment]
Traceback (most recent call last):
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\lexedata\edit\simplify_ids.py", line 54, in <module>
    simplify_table_ids_and_references(ds, table, args.transparent, logger)
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\lexedata\util\simplify_ids.py", line 224, in simplify_table_ids_and_references
    mapping = clean_mapping(cache_table(ds, table.url.string, {}))
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\lexedata\util\__init__.py", line 232, in cache_table
    return {
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\lexedata\util\__init__.py", line 232, in <dictcomp>
    return {
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\csvw\metadata.py", line 770, in iterdicts
    log_or_raise(
  File "C:\Users\spacchia\AppData\Local\Programs\Python\Python310\lib\site-packages\csvw\metadata.py", line 51, in log_or_raise
    raise exception_cls(msg)
ValueError: forms.csv:10975:2 Language_ID: invalid lexical value for string: Ikaan (Ngaliem, DRC)

**Comment by Anaphory** [comment]
Can I get a copy of the dataset you fail with, and the output of `python -c 'import lexedata; print(lexedata.__version__)'` and the exact command you are trying to run? I'd like to bash this issue into submission once and for all.

**Comment by Sara2882** [comment]
This is the output of the command

PS C:\Users\spacchia\Documents\wcb-cwb-data> py -c 'import lexedata; print(lexedata.__version__)'
1.0.2
PS C:\Users\spacchia\Documents\wcb-cwb-data>

**Comment by Anaphory** [comment]
Ah, you run `python -m lexedata.edit.simplify_ids` without a table name. So it probably tries to simplify the FormTable IDs before the LanguageTable IDs. For that it has to read the FormTable, and while reading the forms finds the Language_IDs it doesn't like.

Your bit of the solution for now is to run `python -m lexedata.edit.simplify_ids --tables LanguageTable`. I just tested it, it works with your data.

Our side of the solution is much more difficult, because it means we need to ‘open up’ all the tables, then simplify them, then ‘close’ their data types again, instead of being able to do it table-by-table.

**Comment by Anaphory** [comment]
I just tried to implement a fix. It's quite difficult in the way things are structured right now, so I will have to ponder the whole architecture of `util.simplify_table_ids_and_references`. Please use `--tables TABLENAME` for now to guarantee that the things that need to be fixed first will be fixed first.

**Comment by Anaphory** [comment]
For now I'll add a warning: `"I currently have problems reading data that is not clean, so if I read your FormTable first, but you have IDs that need simplification in your LanguageTable which appear in your FormTable, I will fail with a confusing error. If I do, please try to specify the tables you need simplified using --tables."` before the simplification starts, and `f"I could not simplify your {table}. Maybe try specifying the table with specific ID issues first, using --tables?"` if it fails.

**Comment by nataliacp** [comment]
After importing a new languages using --concept-name-column we ended up with a parameterReference column in forms.csv that had mixed IDs(previous data) and Names(newly imported data). The json still was pointing to the parameter ID column. We tried to simplify IDs on forms.csv (to get the names close to their IDs), but the script wouldn't run at all. Unfortunately, I didn't keep the error, but I think it was about improper IDs. 
After writing all this, I think I know what happened. This was and reference ID column, not and ID column per se! So, there was nothing to simplify (still I don't know why it gave an error though). Should we have simplified the parameters.csv instead?

**Comment by Anaphory** [comment]
I am confused about the other bits, but I can say: If you want simplified Concept (Parameter) IDs, then yes, you want to simplify_ids the ParameterTable.
