### ISSUE TITLE
exporter.cognate is broken on master

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#373]
I tried to export the Bantu dataset and I got this 
```INFO:lexedata:Caching table FormTable
100%|██████████████████████████████████████████████████████████████████████| 12195/12195 [00:00<00:00, 16490.67it/s]
WARNING:lexedata:No Status_Column in CognatesetTable. I will proceed without. Run `lexedata.edit.add_status_column`` in default mode or with table-names CognatesetTable to add a Status_Column.
INFO:lexedata:Caching table LanguageTable
100%|██████████████████████████████████████████████████████████████████████████| 131/131 [00:00<00:00, 30154.98it/s]
INFO:lexedata:Caching table FormTable
100%|██████████████████████████████████████████████████████████████████████| 12195/12195 [00:00<00:00, 17293.90it/s]
INFO:lexedata:Writing languages to excel header
100%|█████████████████████████████████████████████████████████████████████████| 131/131 [00:00<00:00, 620851.78it/s]
INFO:lexedata:Writing rows to Excel
 49%|███████████████████████████████████▊                                     | 1174/2396 [00:00<00:00, 3725.46it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 565, in <module>
    E.create_excel(
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 114, in create_excel
    self.write_row_header(row, r)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/cognates.py", line 262, in write_row_header
    value = self.separators[db_name].join([str(v) for v in cogset[db_name]])
TypeError: 'NoneType' object is not iterable

**Comment by nataliacp** [comment]
I have some more info. the error appears when trying to export automatic singletons. 
WCB-CWB-data$python -m lexedata.exporter.cognates Cognates2.xlsx --add-singletons-with-status "automatic singleton"
the same happens with the shorthand --add-singletons. 
If this argument is omitted, then the cognate table is produced and looks fine, but of course the singletons are not there.

**Comment by nataliacp** [comment]
this is fixed, now, no?
