### ISSUE TITLE
importer error

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#384]
I am trying to import the maweti guarani dataset using the smallmawetiguarani json and it starts seemingly ok, but terminates with an error at about 30% of parsing the comparative wordlist spreadsheet. 
This is my command:
python -m lexedata.importer.excel_matrix TG_comparative_lexical_online_MASTER.xlsx --cogsets TG_cognates_online_MASTER.xlsx --metadata cldf-metadata.json 2>errors.log
and this is what I get:
```
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_matrix.py", line 871, in <module>
    load_dataset(
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_matrix.py", line 804, in load_dataset
    EP.parse_cells(lexicon_wb, status_update=status_update)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_matrix.py", line 402, in parse_cells
    for params in self.cell_parser.parse(
  File "/Users/natalia/Documents/lexedata/src/lexedata/util/excel.py", line 257, in parse
    form = self.parse_form(element, language_id, cell_identifier)
  File "/Users/natalia/Documents/lexedata/src/lexedata/util/excel.py", line 562, in parse_form
    self.postprocess_form(properties, language_id)
  File "/Users/natalia/Documents/lexedata/src/lexedata/util/excel.py", line 730, in postprocess_form
    del properties[self.c["comment"]][-i]
IndexError: list assignment index out of range

**Comment by nataliacp** [comment]
I figured it out. Gereon (who is THE BEST) has made a special loop to catch our NCP: blabla %#5# comments and separate them out. But it seems that it only accepts one such comment per form and Emily had added two! I combined them to one and now it went past 30%
