### ISSUE TITLE
bug in exporter.phylogenetics

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#391]
I ran 
`python3` -m lexedata.exporter.phylogenetics --format nexus --output-file Hilde_matrix.nex --languages Hilde_languages.csv --concepts Hilde_concepts.csv --stats-file Hilde_stats.tex`

and I am getting the following error:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 920, in <module>
    for language, sequence in read_cldf_dataset(dataset).items()
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 86, in read_cldf_dataset
    return read_wordlist(dataset, code_column, logger=logger)
  File "/Users/natalia/Documents/lexedata/src/lexedata/exporter/phylogenetics.py", line 196, in read_wordlist
    (langref_target,) = [
ValueError: too many values to unpack (expected 1)`

I tried looking at the source code, but I can't understand what is going on

**Comment by nataliacp** [comment]
I have tried again removing all arguments step by step to the simplest configuration (full dataset, nexus format) and the error persists

**Comment by nataliacp** [comment]
Sara tried with the released version as well and she gets the exact same error

**Comment by nataliacp** [comment]
the problem was a duplicate foreign key in the FormTable in the json file. Once the duplicate removed, everything is fine.
