### ISSUE TITLE
merge_homophones error message has an error

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#401]
In running merge_homophones, I get the following error message when a merge is attempted but not performed and should be skipped. 
`INFO:lexedata:Going through forms and merging
  0%|                                                                                                               | 0/42772 [00:00<?, ?it/s]ERROR:lexedata:Merging forms: ['62', '535'] with target: 62 on column: Phonemic_Form
The merge function must_be_equal requires the input data to be equal. 
Given input: ['ihiθi', 'ihiʃi']
  1%|█▏                                                                                                | 533/42772 [00:00<00:02, 15461.40it/s]
Traceback (most recent call last):
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 425, in merge_group
    merge_result = merger([form[column] for form in forms], target)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 101, in must_be_equal
    assert c == other_c
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 500, in merge_forms
    buffer[target_id] = merge_group(
                        ^^^^^^^^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 434, in merge_group
    raise Skip
Skip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 675, in <module>
    FormTable=list(
              ^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 513, in merge_forms
    f"Merging form {id} with forms {[f[c_f_id] for f in group]} was skipped."
                                     ~^^^^^^^^
TypeError: string indices must be integers, not 'str'`

**Comment by nataliacp** [comment]
`Traceback (most recent call last):
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 425, in merge_group
    merge_result = merger([form[column] for form in forms], target)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 101, in must_be_equal
    assert c == other_c
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 500, in merge_forms
    buffer[target_id] = merge_group(
                        ^^^^^^^^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 434, in merge_group
    raise Skip
Skip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 675, in <module>
    FormTable=list(
              ^^^^^
  File "/Users/natalia/Documents/lexedata/src/lexedata/edit/merge_homophones.py", line 515, in merge_forms
    del homophone_groups[id]
        ~~~~~~~~~~~~~~~~^^^^
KeyError: '485'`

**Comment by nataliacp** [comment]
fixed now
