### ISSUE TITLE
Give error message and refer to segmenter script, instead of traceback, in edictor exporter

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#98]
```
python -m lexedata.exporter.to_edictor
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gereon/Develop/lexedata/src/lexedata/exporter/to_edictor.py", line 211, in <module>
    forms_to_tsv(
  File "/home/gereon/Develop/lexedata/src/lexedata/exporter/to_edictor.py", line 60, in forms_to_tsv
    c_form_segments = dataset["FormTable", "segments"].name
  File "/home/gereon/.local/etc/lexedata/lib/python3.9/site-packages/pycldf/dataset.py", line 610, in __getitem__
    raise KeyError(column)
KeyError: 'segments'
```

**Comment by Anaphory** [comment]
Do we need an ‘add_cognateset_metadata’ enricher?
```
python -m lexedata.exporter.to_edictor
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gereon/Develop/lexedata/src/lexedata/exporter/to_edictor.py", line 211, in <module>
    forms_to_tsv(
  File "/home/gereon/Develop/lexedata/src/lexedata/exporter/to_edictor.py", line 95, in forms_to_tsv
    for c, cognateset in enumerate(dataset["CognatesetTable"], 1)
  File "/home/gereon/.local/etc/lexedata/lib/python3.9/site-packages/pycldf/dataset.py", line 598, in __getitem__
    raise KeyError(table)
KeyError: 'CognatesetTable'

```

**Comment by nataliacp** [comment]
I don't understand what it would enrich cognatesets with. Can you give some
more info?

**Comment by Anaphory** [comment]
As I said, I don't know either. But it might be useful if there's no CognatesetTable (can totally happen in some workflows) to add a trivial one. And then the question is
1. Do we want to build that? It's pretty trivial, but still a bit of bloat.
2. If we want to build it, is there something else that it could sensibly guess from the data which isn't already in another one of our scripts?

**Comment by nataliacp** [comment]
ok, now i see. I think it makes sense to have something that would make the
cognatesetTable. Right now, for the bantu dataset what is happening? if I
remember correctly there is no metadata associated with cognate sets, only
numbers of which form belongs where. I can't think off the top of my head
of another workflow that wouldn't have any cognateset metadata. So, if a
minimal table is created from a dataset a la Bantu, I think it is ok. Then
the only thing I can imagine can be guessed is the core concept, which has
a script already. So, you run the script on the minimal table you created
when you imported, and then a column for core concept is added. am I
missing something? we can also discuss this next week.

**Comment by Anaphory** [comment]
That commit is a side track from the original issue, which is about the edictor exporter not giving good error messages.

**Comment by Anaphory** [comment]
I have now added such a message.
```
WARNING:lexedata:No segments found for form mozambican_tonga_wind. You can generate segments using `lexedata.enrich.segment_using_clts`.
```
but the edictor exporter seems to maybe skip those forms? Maybe it has another reason my cognate.tsv is empty, though. Gonna glue in some segments and see.

**Comment by Anaphory** [comment]
Okay, that wasn't the reason.
